/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcoesCmp: typeof import('./src/components/editor/body/painelHome/acoes/AcoesCmp.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BodyCmp: typeof import('./src/components/editor/body/BodyCmp.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardItemCmp: typeof import('./src/components/editor/body/painelHome/card/CardItemCmp.vue')['default']
    ConfirmDialogCmp: typeof import('./src/components/editor/toolbar/ConfirmDialogCmp.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FooterCmp: typeof import('./src/components/editor/footer/FooterCmp.vue')['default']
    HomeBodyCmp: typeof import('./src/components/home/body/HomeBodyCmp.vue')['default']
    HomeCardItemCmp: typeof import('./src/components/home/body/components/recentes/HomeCardItemCmp.vue')['default']
    HomeFooterCmp: typeof import('./src/components/home/footer/HomeFooterCmp.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    PanelFormCmp: typeof import('./src/components/home/body/components/PanelFormCmp.vue')['default']
    PanelHomeCmp: typeof import('./src/components/home/body/components/PanelHomeCmp.vue')['default']
    PreviewCodigoCmp: typeof import('./src/components/editor/body/painelPreview/PreviewCodigoCmp.vue')['default']
    PreviewHtmlCmp: typeof import('./src/components/editor/body/painelPreview/PreviewHtmlCmp.vue')['default']
    RecentesCmp: typeof import('./src/components/home/body/components/recentes/RecentesCmp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    ToolbarAcoesCmp: typeof import('./src/components/editor/toolbar/ToolbarAcoesCmp.vue')['default']
    ToolbarCmp: typeof import('./src/components/editor/toolbar/ToolbarCmp.vue')['default']
    ToolbarConfigCmp: typeof import('./src/components/editor/toolbar/ToolbarConfigCmp.vue')['default']
    ToolbarLogoCmp: typeof import('./src/components/editor/toolbar/ToolbarLogoCmp.vue')['default']
  }
}
