/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BodyCmp: typeof import('./src/components/body/BodyCmp.vue')['default']
    BodyItemCmp: typeof import('./src/components/body/BodyItemCmp.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardItemCmp: typeof import('./src/components/body/CardItemCmp.vue')['default']
    copy: typeof import('./src/components/toolbar/ToolbarConfigCmp copy.vue')['default']
    Div: typeof import('./src/components/body/div.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FooterCmp: typeof import('./src/components/footer/FooterCmp.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemCmp: typeof import('./src/components/body/ItemCmp.vue')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    PanelPrincipal: typeof import('./src/components/body/PanelPrincipal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    ToolbarAcoesCmp: typeof import('./src/components/toolbar/ToolbarAcoesCmp.vue')['default']
    ToolbarCmp: typeof import('./src/components/toolbar/ToolbarCmp.vue')['default']
    ToolbarConfig: typeof import('./src/components/toolbar/ToolbarConfig.vue')['default']
    ToolbarConfigCmp: typeof import('./src/components/toolbar/ToolbarConfigCmp.vue')['default']
    ToolbarLogoCmp: typeof import('./src/components/toolbar/ToolbarLogoCmp.vue')['default']
  }
}
